SOURCESCPP-y+=long_numbers.o
SOURCESCPP-y+=long_mumbers_arithmetic.o
SOURCESCPP-y+=long_numbers_binary_ops.o

#$(SOURCESCPP-y): %.o : %.cpp
#	g++ -c $(CFLAGS)  $< -o $(LIB_OBJ)/$@ -g -O0
#	$(S)echo g++: $@

include $(CRYPTO_LIB)/build.src.mk
